import { ArrowUpDown, RefreshCw, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { CategoryFilter, NewsGrid } from '../components/news/NewsCard'
import { LoadingSkeleton } from '../components/ui/UI'
import { categories } from '../data/mockNews'

export default function News({ articles, onToggleSave, showToast }) {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const [sort, setSort] = useState('latest'); const [loading, setLoading] = useState(false)
  const displayed = useMemo(() => articles.filter(a => (category === 'All' || a.category === category) && `${a.title} ${a.summary} ${a.source}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === 'importance' ? ({ High: 3, Medium: 2, Low: 1 }[b.importance] - { High: 3, Medium: 2, Low: 1 }[a.importance]) : 0), [articles, category, query, sort])
  function refresh() { setLoading(true); setTimeout(() => { setLoading(false); showToast('Your news feed is up to date.'); }, 850) }
  return <div className="mx-auto max-w-[1440px] space-y-7 p-5 sm:p-7 lg:p-9"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="page-title">Latest news</h2><p className="mt-2 subtle">Discover the latest technology news, summarized by AI.</p></div><button onClick={refresh} disabled={loading} className="btn-secondary"><RefreshCw size={16} className={loading ? 'animate-spin' : ''} />Refresh</button></section><section className="panel p-4"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} className="control pl-10" placeholder="Search the news" /></label><label className="relative"><ArrowUpDown size={16} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><select value={sort} onChange={e => setSort(e.target.value)} className="control appearance-none pl-9 pr-9"><option value="latest">Latest first</option><option value="importance">Most important</option></select></label></div><div className="mt-4"><CategoryFilter value={category} onChange={setCategory} categories={categories} /></div></section>{loading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3,4,5,6].map(i => <div className="panel p-5" key={i}><LoadingSkeleton /></div>)}</div> : displayed.length ? <NewsGrid articles={displayed} onToggleSave={onToggleSave} /> : <div className="panel py-16 text-center"><h3 className="font-semibold">No stories found</h3><p className="mt-1 text-sm text-slate-500">Try another topic or search phrase.</p></div>}</div>
}
