import { ArrowRight, BookOpen, CalendarClock, ChevronRight, Clock3, Cpu, Mail, Newspaper, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { NewsGrid } from '../components/news/NewsCard'

function Metric({ icon: Icon, label, value, note, tone = 'blue' }) { const tones = { blue: 'bg-blue-50 text-blue-600', violet: 'bg-violet-50 text-violet-600', amber: 'bg-amber-50 text-amber-600', emerald: 'bg-emerald-50 text-emerald-600' }; return <div className="panel p-4"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">{label}</span><span className={`grid h-8 w-8 place-items-center rounded-lg ${tones[tone]}`}><Icon size={16} /></span></div><p className="mt-5 text-2xl font-semibold tracking-[-0.04em] text-slate-800">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></div> }

export default function Overview({ articles, onToggleSave, showToast }) {
  return <div className="mx-auto max-w-[1440px] space-y-8 p-5 sm:p-7 lg:p-9">
    <section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 flex items-center gap-2 text-sm font-medium text-blue-600"><span className="h-1.5 w-1.5 rounded-full bg-blue-600" />Tuesday, October 6</p><h2 className="page-title">Your personal tech briefing</h2><p className="mt-2 subtle">Stay informed about the technology that matters to you.</p></div><Link to="/digest" className="btn-primary"><Mail size={17} />Preview email</Link></section>
    <section className="relative overflow-hidden rounded-2xl bg-slate-900 px-6 py-6 text-white shadow-lg shadow-slate-200 sm:px-8 sm:py-7"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-blue-500/20 blur-3xl" /><div className="relative grid gap-6 lg:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2 text-sm font-semibold text-blue-200"><Sparkles size={17} />Daily briefing</div><h3 className="mt-3 text-2xl font-semibold tracking-[-0.03em]">Your next briefing is on its way</h3><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">A focused round-up of the news you care about, selected and summarized for your morning.</p><div className="mt-6 grid grid-cols-2 gap-x-7 gap-y-4 text-sm sm:grid-cols-4"><div><p className="text-xs text-slate-400">Scheduled</p><p className="mt-1 font-medium">Every weekday</p></div><div><p className="text-xs text-slate-400">Next delivery</p><p className="mt-1 font-medium">Tomorrow, 8:00 AM</p></div><div><p className="text-xs text-slate-400">Recipient</p><p className="mt-1 font-medium">karthik@example.com</p></div><div><p className="text-xs text-slate-400">Reading time</p><p className="mt-1 font-medium">About 6 minutes</p></div></div></div><button onClick={() => showToast('Email preview is ready in your digest settings.')} className="btn-secondary self-start border-white/15 bg-white/10 text-white hover:border-white/25 hover:bg-white/20"><BookOpen size={17} />Preview email</button></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Newspaper} label="Today’s news" value="24" note="6 new since this morning" /><Metric icon={Cpu} label="AI processed" value="18" note="Tailored to your interests" tone="violet" /><Metric icon={BookOpen} label="Saved articles" value={articles.filter(a => a.saved).length} note="Read them when you’re ready" tone="amber" /><Metric icon={CalendarClock} label="Next digest" value="16h" note="Wednesday, 8:00 AM" tone="emerald" /></section>
    <section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-lg font-semibold tracking-[-0.02em] text-slate-800">Latest news</h2><p className="mt-1 subtle">A quick scan of what’s shaping technology today.</p></div><Link to="/news" className="hidden items-center gap-1 text-sm font-semibold text-blue-600 hover:text-blue-700 sm:flex">View all news <ChevronRight size={17} /></Link></div><NewsGrid articles={articles.slice(0, 3)} onToggleSave={onToggleSave} compact /><Link to="/news" className="btn-secondary mt-4 w-full sm:hidden">View all news <ArrowRight size={16} /></Link></section>
  </div>
}
